name: Daily Data Collection

on:
  workflow_dispatch:
  schedule:
    # midnight us
    - cron: '0 5 * * *'

jobs:
  run-collector:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./collector 

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Debug Secrets
        run: echo "DB_HOST starts with ${{ secrets.DB_HOST && substring(secrets.DB_HOST, 0, 5) || 'is not set' }}"

      - name: Run data collector script
        run: python main.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
